# Copyright (c) 2023 The Android Open Source Project
# Copyright (C) 2023 SebaUbuntu's TWRP device tree generator 4-#
# SPDX-License-Identifier: Apache-2.0
#
# 关于橙狐变量详见 fox_12.1/vendor/recovery/orangefox_build_vars.txt 

OF_MAINTAINER := nanya 
 
#display for pad
 
OF_SCREEN_DPI := 704
OF_DYNAMIC_FULL_SIZE := 14578294784

OF_ENABLE_ALL_PARTITION_TOOLS := 1
OF_WORKAROUND_BACKUP_BUG := 1
OF_USE_AIDL_BOOT_CONTROL := 0
OF_UNBIND_SDCARD_F2FS := 1
OF_WIPE_METADATA_AFTER_DATAFORMAT := 1
OF_DISPLAY_FORMAT_FILESYSTEMS_DEBUG_INFO := 1
OF_NO_RELOAD_AFTER_DECRYPTION := 1
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
OF_RECOVERY_AB_FULL_REFLASH_RAMDISK := 1

OF_USE_LZ4_COMPRESSION := 1
OF_ENABLE_FS_COMPRESSION := 1
 
 # OTA
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_PATCH_AVB20 := 1
OF_KEEP_DM_VERITY_FORCED_ENCRYPTION := 1
